version: "3.9"


networks:
  ebook-network:
    driver: bridge

services:

  data-quality-module:
    build:
      context: ./data-quality-module
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    environment:
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
    networks:
      - ebook-network
    restart: on-failure

  bff-gateway:
    build:
      context: ./bff-gateway
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    environment:
      DATA_QUALITY_URL: ${DATA_QUALITY_URL}
      
      AUTH_SERVICE_URL:      ${AUTH_SERVICE_URL}
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
      CATALOG_SERVICE_URL:   ${CATALOG_SERVICE_URL}
      AI_ENRICHMENT_URL:     ${AI_ENRICHMENT_URL}
      CONFIG_MODULE_URL:     ${CONFIG_MODULE_URL}
    depends_on:
      - data-quality-module
    networks:
      - ebook-network
    restart: on-failure
